export type OrganismMood =
  | "transcendent" | "thriving" | "content"
  | "thirsty" | "dormant" | "decaying" | "critical";

export type Season = "bloom" | "mist" | "golden_decay" | "neon_rain";

export type CreatureType =
  | "butterfly" | "moth" | "jellyfish" | "firefly" | "bird" | "spore";

export type ActivityType =
  | "watering" | "bloom" | "mutation" | "decay" | "creature"
  | "season" | "milestone" | "rare_event" | "micro_evolution";

export interface OrganismState {
  id: string;
  hydration: number;
  growth: number;
  decay: number;
  mutationLevel: number;
  beautyLevel: number;
  biodiversity: number;
  ecosystemStage: number;
  mood: OrganismMood;
  season: Season;
  totalWaterings: number;
  totalUsers: number;
  leafCount: number;
  uniqueWaterersCount: number;
  lastWatered: string;
  updatedAt: string;
}

export interface LeafData {
  id: string;
  username: string;
  color: string;
  posX: number;
  posY: number;
  posZ: number;
  scale: number;
  rotation: number;
}

export interface ActivityEntry {
  id: string;
  type: ActivityType;
  message: string;
  username?: string;
  metadata?: Record<string, unknown>;
  createdAt: string;
}

export interface BloomEvent {
  flowerType: string;
  position: [number, number, number];
}

export interface CreatureSpawnEvent {
  type: CreatureType;
  id: string;
}

export interface MutationEvent {
  level: number;
  description: string;
}

export interface MicroEvolutionEvent {
  message: string;
  waterings: number;
}

export interface RareEvent {
  name: string;
  description: string;
}

export interface WateringEffect {
  username: string;
  sessionId: string;
  amount: number;
}

export interface LeavesUpdateEvent {
  leaves: LeafData[];
}

// ─────────────────────────────────────────────────────────
// 100 Stage Names
// ─────────────────────────────────────────────────────────
export const ECOSYSTEM_STAGE_NAMES: Record<number, string> = {
  1:   "Awakening Seed",        2:  "First Root",           3:  "Soft Tendril",
  4:   "Micro Sprout",          5:  "Budding Life",         6:  "Moss Fragment",
  7:   "Young Shoot",           8:  "Reaching Vine",        9:  "Breathing Plant",
  10:  "Living Thing",          11: "Fern Child",           12: "Lush Frond",
  13:  "Spiral Growth",         14: "Light Seeker",         15: "Dew Catcher",
  16:  "Forest Whisper",        17: "Root Network",         18: "Canopy Dreamer",
  19:  "Ancient Fern",          20: "Dream Fern",           21: "Night Bloom",
  22:  "Petal Storm",           23: "Nectar Heart",         24: "Fragrant Soul",
  25:  "Blossom World",         26: "Pollen Cloud",         27: "Spore Singer",
  28:  "Mycelium Mind",         29: "Fungal Dream",         30: "Violet Bloom",
  31:  "Crystal Vein",          32: "Glass Garden",         33: "Quartz Life",
  34:  "Faceted Soul",          35: "Gem Organism",         36: "Diamond Fern",
  37:  "Prismatic Web",         38: "Refracted Dream",      39: "Resonant Crystal",
  40:  "Crystalline Mind",      41: "Static Garden",        42: "Charged Tendril",
  43:  "Lightning Root",        44: "Electric Flower",      45: "Plasma Fern",
  46:  "Neon Bloom",            47: "Voltage Life",         48: "Arc Garden",
  49:  "Pulse Organism",        50: "Plasma Heart",         51: "Nebula Seed",
  52:  "Star Nursery",          53: "Void Tendril",         54: "Dark Garden",
  55:  "Gravity Bloom",         56: "Quantum Fern",         57: "Singularity Life",
  58:  "Event Horizon",         59: "Spacetime Garden",     60: "Stellar Bloom",
  61:  "Solar Root",            62: "Photon Garden",        63: "Radiant Life",
  64:  "Sunheart Bloom",        65: "Dawn Organism",        66: "Zenith Garden",
  67:  "Apex Life",             68: "Crown Bloom",          69: "Solar Mind",
  70:  "Sun God Garden",        71: "Pure Light Root",      72: "Energy Fern",
  73:  "Consciousness Bloom",   74: "Dream Organism",       75: "Soul Forest",
  76:  "Mind Garden",           77: "Spirit Bloom",         78: "Awareness Life",
  79:  "Thought Garden",        80: "Transcendent Heart",   81: "Celestial Seed",
  82:  "Angel Fern",            83: "Heaven Bloom",         84: "Divine Garden",
  85:  "Sacred Life",           86: "Holy Organism",        87: "Eternal Bloom",
  88:  "Infinite Garden",       89: "Boundless Life",       90: "Celestial Entity",
  91:  "Omniversal Root",       92: "Reality Fern",         93: "Existence Bloom",
  94:  "Universe Garden",       95: "All-Life",             96: "Cosmic Oversoul",
  97:  "Dream Entity",          98: "Living Universe",      99: "Pure Bloom World",
  100: "The Dream Absolute",
};

// ─────────────────────────────────────────────────────────
// Stage Colors — generated by interpolating 11 key stages
// Glow colors are deliberately kept below 0.70 luminance
// so the organism body NEVER triggers bloom (threshold 0.78)
// Only accent colors (branch tips, crystal edges) are bright
// ─────────────────────────────────────────────────────────
type StageColor = { core: string; glow: string; accent: string; fog: string };

function lerpHex(c1: string, c2: string, t: number): string {
  const p = (h: string, i: number) => parseInt(h.slice(1 + i * 2, 3 + i * 2), 16);
  const lerp = (a: number, b: number) =>
    Math.round(a + (b - a) * t).toString(16).padStart(2, "0");
  return `#${lerp(p(c1, 0), p(c2, 0))}${lerp(p(c1, 1), p(c2, 1))}${lerp(p(c1, 2), p(c2, 2))}`;
}

const KEY_STAGE_COLORS: [number, StageColor][] = [
  [ 1,  { core: "#0e2208", glow: "#1a6812", accent: "#58f020", fog: "#030803" }], // Seed — deep green
  [12,  { core: "#0a3318", glow: "#1a9040", accent: "#30ffa0", fog: "#030d07" }], // Lush — jade green
  [22,  { core: "#083a3a", glow: "#0ea8a8", accent: "#20ffee", fog: "#030e0e" }], // Fern — cyan
  [32,  { core: "#280a38", glow: "#8025b0", accent: "#e050ff", fog: "#0d030e" }], // Bloom — purple
  [42,  { core: "#0a0a30", glow: "#1840c0", accent: "#50a0ff", fog: "#03030d" }], // Crystal — blue
  [52,  { core: "#1a0a3a", glow: "#5018b0", accent: "#c050ff", fog: "#08030e" }], // Plasma — violet
  [62,  { core: "#2e0a08", glow: "#b02010", accent: "#ff5828", fog: "#0d0403" }], // Solar — red-orange
  [72,  { core: "#2a2008", glow: "#a09000", accent: "#ffd000", fog: "#0d0a03" }], // Gold — amber
  [82,  { core: "#081828", glow: "#1868b0", accent: "#48c0ff", fog: "#030608" }], // Nebula — sky blue
  [92,  { core: "#180828", glow: "#7028b0", accent: "#c850ff", fog: "#07030e" }], // Cosmic — deep purple
  [100, { core: "#141428", glow: "#3838a8", accent: "#8888ff", fog: "#040408" }], // Absolute — cosmic indigo
];

function buildStageColors(): Record<number, StageColor> {
  const result: Record<number, StageColor> = {};
  for (let stage = 1; stage <= 100; stage++) {
    let lowerIdx = 0;
    for (let i = 0; i < KEY_STAGE_COLORS.length - 1; i++) {
      if (KEY_STAGE_COLORS[i]![0] <= stage && KEY_STAGE_COLORS[i + 1]![0] >= stage) {
        lowerIdx = i;
        break;
      }
    }
    const [lStage, lCol] = KEY_STAGE_COLORS[lowerIdx]!;
    const [uStage, uCol] = KEY_STAGE_COLORS[lowerIdx + 1] ?? KEY_STAGE_COLORS[KEY_STAGE_COLORS.length - 1]!;
    const t = lStage === uStage ? 0 : (stage - lStage) / (uStage - lStage);
    result[stage] = {
      core:   lerpHex(lCol.core,   uCol.core,   t),
      glow:   lerpHex(lCol.glow,   uCol.glow,   t),
      accent: lerpHex(lCol.accent, uCol.accent, t),
      fog:    lerpHex(lCol.fog,    uCol.fog,    t),
    };
  }
  return result;
}

export const STAGE_COLORS: Record<
  number,
  { core: string; glow: string; accent: string; fog: string }
> = buildStageColors();

export const MOOD_DESCRIPTIONS: Record<OrganismMood, string> = {
  transcendent: "Beyond existence — pure light",
  thriving:     "Radiating impossible beauty",
  content:      "Breathing softly, peacefully",
  thirsty:      "Reaching for water, for care",
  dormant:      "Sleeping, waiting to be found",
  decaying:     "Wilting into beautiful ruin",
  critical:     "On the edge of silence",
};

export const SEASON_DESCRIPTIONS: Record<Season, string> = {
  bloom:        "Everything blooms simultaneously",
  mist:         "Fog drifts through the canopy",
  golden_decay: "Beauty in its most honest form",
  neon_rain:    "Electric storms feed the roots",
};
